### ISSUE TITLE
Question: can the same animation be done for when switching between CardViews?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [sahildave/Search-View-Layout#10]
Suppose I have multiple CardViews with different content and size, is it possible to animate between them nicely, so that it looks like the CardView changes its size?

**Comment by sahildave** [comment]
You can try and use the Utils#crossfadeViews method.

https://github.com/sahildave/Search-View-Layout/blob/master/searchviewlayout/src/main/java/xyz/sahildave/widget/Utils.java#L69

**Comment by AndroidDeveloperLB** [comment]
@sahildave I'm not talking about fade in&out. I'm talking about scaling...
Here, I've made a StackOverflow question:
http://stackoverflow.com/questions/34069348/how-to-smooth-animate-between-cardviews-of-different-sizes
