### ISSUE TITLE
Too small touch target for the back arrow

### ISSUE THREAD

**Issue by balazsgerlei** [sahildave/Search-View-Layout#13]
While I like the design and behaviour of this lib a lot, there is a small, but important hurdle with it: when the search layout is expanded, the back arrow displayed on the left side has a way too small touch target. I think the best would be as high as the whole search layout, and the same width too (so it retains the 1:1 ratio).

Now it's barely bigger than the arrow itself and really easy to miss. Please correct it, it would improve the usability a lot!

**Comment by sahildave** [comment]
Also. The touchDelegate for Search icon on the right side of layout has a small width. I am aware of this issue myself.
