### ISSUE TITLE
Support v4 fragment

### ISSUE THREAD

**Issue by EpsilonOrionis** [sahildave/Search-View-Layout#14]
I'm trying to launch a support.v4.fragment, but I get Wrong 2nd type argument, how can I solve this?

**Comment by balazsgerlei** [comment]
Yes it would be good if the library would support the supoort library version of fragments!

**Comment by sahildave** [comment]
Hi. I would try to do this through the weekened. If you want, you create a PR for this issue.

**Comment by balazsgerlei** [comment]
I've done a pull request with a fix. Although the CircleCI failed on it with a message: "> Gradle version 2.2 is required. Current version is 1.10."

I'm not sure why is this, although I have to say I never used CircleCI before. Do you have any idea?

**Comment by petermajor** [comment]
Any chance of getting this merged and released? I'd really like to be able to use the aar rather than modify the source and include it into our project...

**Comment by sahildave** [comment]
Hi @petermajor I am sorry I have been under the weather lately, away from my system. Would still take me a week or more to recover. If it is urgent can you use @balazsgerlei's PR in the meantime?

Hope you understand

**Comment by kiaanpillay** [comment]
I would also love this please! Get better!

**Comment by kiaanpillay** [comment]
From what I can see there are no issues on the PR, if you could merge it when you have a chance that would be really appreciated. This is a brilliant lib! One of the few search libs that work smoothly

**Comment by kiaanpillay** [comment]
Any progress?

**Comment by kiaanpillay** [comment]
Hi, thanks for the lib Sahildave, really nice. This merge would really help me! Any idea ehen you can do it?

**Comment by jojodevjo** [comment]
Hi Sahildave, thanks for the library. Very nice. This fix will really help me, when will it be out?

**Comment by sahildave** [comment]
Hi. I'll be doing this tomorrow. By 9 PM IST.

Thanks guys.

**Comment by kiaanpillay** [comment]
Yessss! Thank you so much. Life saver!

**Comment by kiaanpillay** [comment]
Hi, I am still not able to get it to work.

I am doing this searchViewLayout.setExpandedContentFragment(getActivity(), new SearchContainerFragment());

Where SearchContainerFragment is a android.support.v4.app.Fragment;

It says it requires android.app.Fragment

**Comment by balazsgerlei** [comment]
Hi!
Since I implemented the pull request, I can answer your question on that one. I added a separate method for using Support version of fragments, to adhere to the policy that Android uses in support libraries.
So if you would like to use support fragments, you have to call `setExpandedContentSupportFragment` instead of `setExpandedContentFragment`.

**Comment by balazsgerlei** [comment]
One can maybe argue if it would be better to call it `setSupportExpandedContentFragment`but I found it sounding weird.

**Comment by kiaanpillay** [comment]
Oh perfect! I Should have spotted that. My oversight! Thank you all
