### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by ajans** [sahildave/Search-View-Layout#19]
I am evaluating the use of your Search-View-Layout library in our closed-source app.
Unfortunately, the LICENSE-file in the root-folder specifies the usage of your library according to the GPL-2.0 license, which demands full source code disclosure even for the apps using your library.

As it is not an option for me to disclose the apps' source code, I would like to propose a license-change to 

http://www.apache.org/licenses/LICENSE-2.0

in order to enable developers of commercial apps to use your great library.

If you want, I could create a pull request with the license-change from my forked repository.

**Comment by sahildave** [comment]
Yes. Please do. Thanks.
