### ISSUE TITLE
When expanding with tab layout fragment gets cut off at bottom

### ISSUE THREAD

**Issue by kiaanpillay** [sahildave/Search-View-Layout#25]
I am using ExpandedContentSupportFragment to expand a fragment that contains tabs, If I go into any of these tabs the bottom bit is cut off, almost as if there is a bit off the screen that can never be seen. Is there any fix to this?

**Comment by sahildave** [comment]
Hey can you add a screenshot of this? I am using (regular) Fragment with a scrollview in my app and it works fine. Can you refer the sample app and also check the layout xmls of your viewpager?

**Comment by kiaanpillay** [comment]
I actually think I fixed it by adding a layoutMargin to the bottom of the viewpager, the margin was 54dp(Search bar)+48dp(Tab Layout)=102dp

I can still post a screen if you think it may help anyone else with the issue? Otherwise we can close this?
