### ISSUE TITLE
Bug: not a nice animation when going back to the previous activity

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [sahildave/Search-View-Layout#3]
Looks like this:
![clip0033](https://cloud.githubusercontent.com/assets/5357526/11170651/2df2d8f6-8be3-11e5-987e-c6e013ea109f.gif)

**Comment by AndroidDeveloperLB** [comment]
Also, BTW, Android-Studio refused to import the project normally, so I had to clone it and only then import it.

**Comment by sahildave** [comment]
@AndroidDeveloperLB Yes. Have to use `onAnimationUpdate` and use the animation factor and set padding accordingly.

**Comment by AndroidDeveloperLB** [comment]
Can you please fix it?

**Comment by AndroidDeveloperLB** [comment]
So it got fixed?

**Comment by sahildave** [comment]
Yes. Check this the new demo gif in the README.md

**Comment by AndroidDeveloperLB** [comment]
@sahildave Nice ! Thank you !
