### ISSUE TITLE
Unable to scroll expanded fragment

### ISSUE THREAD

**Issue by 3lywa** [sahildave/Search-View-Layout#4]
I've implemented a viewpager + tabs as the expanded fragment. Each viewpager has a recyclerview. I'm able to swipe left and right with no problems, however, swipping up/down is not possible!

**Comment by sahildave** [comment]
Can you fork the repo and create a demo?

**Comment by 3lywa** [comment]
Demo created at https://github.com/3lywa/Search-View-Layout

Please let me know if you have any questions.

**Comment by sahildave** [comment]
Hey @3lywa You need to intercept the touch event and disallow the parent. Use this in your project. Refer the sample for more.

``` java
stops.setOnTouchListener(new View.OnTouchListener() {
    // Setting on Touch Listener for handling the touch inside ScrollView
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        // Disallow the touch request for parent scroll on touch of child view
        v.getParent().requestDisallowInterceptTouchEvent(true);
        return false;
    }
});
```

**Comment by 3lywa** [comment]
Thank you for the quick response @sahildave, i tried the sample and its working fine now!

**Comment by suleymanccelik** [comment]
Hi,

When I set SearchStaticRecyclerFragment as expanded content of search view layout, I get the same issue. I am running your sample. 

My test phones are LG G3 ( android 5.0 ) and Android One General Mobile ( Android 6.0 ).
