### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by EpsilonOrionis** [sahildave/Search-View-Layout#6]
Is there a way to set a hint?

**Comment by vguzzi** [comment]
@EpsilonOrionis There isn't currently a way to set a hint. `mSearchEditText` is also set to private so you can't set a hint yourself. I can implement a set custom hint method or an optional constructor `String` tonight and request a merge if you need it.

**Comment by EpsilonOrionis** [comment]
Yes thank you, it would be great!

**Comment by EpsilonOrionis** [comment]
Hi, how can I use your changes in my code?

**Comment by vguzzi** [comment]
You can just go to my profile and take my version of search view layout for now until I update it to be synced with the main branch.

**Comment by sahildave** [comment]
Added in 0.1

Check the readme.

**Comment by EpsilonOrionis** [comment]
Thank you ;)
